### PR TITLE
Custom columns

### LINKED ISSUE #85: Request - customizable columns in setlist/owned view
## Sortable

- Ability to pick order of columns (either drag-n'-drop, or just a setting somewhere)
  - So you could go Artist -> Song -> ... instead of Song -> Artist

## Customizable

- Ability to customize columns shown (either drag-n'-drop, or just a setting somewhere)
- For examples...
  - I don't care about album when picking songs to play, so I'd like to hide that one 
  - I'd love to be able to add `duration` 
  - I'd love to be able to add last-played
- Anything not shown in the table could still show in the detail popup

### PR DESCRIPTION
**Pull request by sandiz**
fixes #85

### CODE REVIEW

**Comment by sandiz** [comment]
@JustinAiken could you take a look at the custom columns (whenever possible, no rush 😇 ) and see if your use cases are covered, prerelease builds are here https://github.com/sandiz/rs-manager/releases/tag/untagged-2d7a10824de0b37532ea

**Comment by JustinAiken** [comment]
- The settings is a bit clunky; it would let me remove, but clicking "Add" didn't do anything, and I couldn't add them by typing or rearrangement...
  - But I edited `config.json` to fix the order
- Once setup, absolutely perfect! 

Thanks for adding!! :)

**Comment by sandiz** [comment]
thanks for the feedback! right now, if the item is already in the list, clicking on add for the same item moves it to the last position which is definitely not intuitive. 

couple of things i am gonna try
1. type to add item 
2. drag drop rearrange of the list

**Comment by sandiz** [comment]
merging this, using a new branch for improvements

**Pull request merged**
